### ISSUE TITLE
[1.10.2] Transfer Upgrade not craftable

### ISSUE THREAD

**Issue by b0bst3r** [SonarSonic/Calculator#129]
Calculator-1.9.4-3.0.3
SonarCore-1.9.4-3.0.4
Forge 2008

Not sure if you implemented it or not but all the other upgrades seem to be.  The transfer upgrade doesn't seem to have any recipe at all.

**Comment by tommyTT** [comment]
Check the new fabrication chamber block, you can get it through there. The way it works is to put it down next to a storage chamber with circuit in them, select the item you wand and then click Fabricate. Wait a moment and go out of the GUI, so you can see the little arms work and after a few seconds the item should be available.

I like the idea of the block but the model kind of freaks me out. It looks like a face when I stand in front of it and the first time I felt like it was mocking me, because I couldn't figure out how it actually works. I would suggest some sort of progress bar inside the GUI, because the animation of the block is a little too subtle, especially while the GUI is open. Of course, a tool tip for the transfer upgrade and the warp module would also be helpful (maybe a mention in the info calculator).

**Comment by SonarSonic** [comment]
I've implemented a recipe now. Yeah you can use the Fabrication Chamber instead.

**Comment by b0bst3r** [comment]
I made several transfer upgrades and clicked them into relevant sides I wanted to transfer items out of but they don't move, tried machine against machine and tried using EIO item transfer pipes.  Any clues as to how to get stuff moving?

**Comment by SonarSonic** [comment]
You need to shift click the sides you want to transfer out of with a wrench. Also I've added a separate recipe for the Transfer Upgrade
