### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by whitehat101** [SonarSonic/Calculator#178]
I'm considering contributing to your mod, but I'm confused by your choice of license and additional conditions.

Your extra conditions:

> Full credit must always be given to me.
> No re-releases of any form unless I have given expressed permission

Negates what the MIT license is trying to achieve:

> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software

Here is a plain English breakdown of the MIT: https://tldrlegal.com/license/mit-license

If you don't want people to modify, distribute, publish, or fork your code, and you don't want contributors to receive credit for their contributions, then the MIT license is not the right license for your project.

**Comment by SonarSonic** [comment]
Well to be honest I'm no expert on licenses. Basically you're free to modify and fork however you want but you can't distribute or publish without my permission. Hope that makes more sense. I'll change it if it's not clear enough.

**Comment by AEnterprise** [comment]
it indeed negates the MIT licence, i think @SonarSonic is just trying to avoid people distributing his mod pretending they made it

in MC modding the 'full credit' is pretty common since the bukkit drama, intended to prevent people from contributing to something and then if they for some reason don't agree with the project or others involved in it issue a DMCA because it uses their code
