### ISSUE TITLE
Item Dupe with Analysing Chamber

### ISSUE THREAD

**Issue by ShadowWolf666** [SonarSonic/Calculator#206]
Please fill out the details below before contributing

 * Forge Version: 12.18.2.2221
 * Calculator Version: 3.1.6
 * SonarCore Version: 3.2.1
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: No Crash (Dupe)
 * Affected Features: Unintended duping with Analysing Chamber and Enderio Item Conduits
 * Description: My setup is like this: Processing Chamber uses Enderio Conduits to feed unanalyzed circuits in to the chamber, and the chamber exports with Enderio conduits out the other side (input right, output left). However, this doesn't pull out the extra items, just the analyzed circuits, so I originally tried putting another Enderio conduit attached on to the back of the Analysing Chamber. This conduit did pull the item from the secondary inventory, but with one flaw: It doesn't actually pull the item, it just sits there in the Analysing Chamber, duping over and over, filling up my chest with the item without ever removing it from the Chamber's inventory. If I pull the item out by hand during this time, it moves on to the next circuit until it hits the next secondary output, by which it starts duping again. Am I doing something wrong? How can I fix this? As fun as this might sound, I'm trying to cycle through drops, don't need infinite grenades.

(Using "All the Mods" modpack if that helps.)

**Comment by Ruchian** [comment]
The sides of the Analyzing Chamber can be configured to either red or green. Green is for circuits and Red for items. These count as both input and output for these slots.
You can change the side configuration with a wrench. (only with the wrench from Calculator)

You can turn some analysed circuits into upgrades. One of them in the transfer upgrade. When you use this on the Analysing Chamber, it willl attempt to automatically output to a side with a block that accepts input next to it. This will allow you to skip using stuff from other mods, such as ender io conduits and place blocks next to one another another instead.
Another thing you maybe want to know of is the Void Upgrade. When you install this into the Analysing chamber, it will simply discard the secondary outputs (the items) and only keep the circuits.
There's no clear explanation of these items anywhere, if you wonder. The reason maybe because these upgrades react a little bit differently on each machine and may not even install which is the case with most of the machines.
You can install an upgrade by right click using it on one. Instead of opening the interface of the machine, you should get a message in your chat box.

I hope that this information will satisfy you for now.

**Comment by ShadowWolf666** [comment]
Helpful information that I mostly didnt know, but theres still the dupe to look at. At least ill be able to get the secondaries out without exploiting :p thanks.



On Thu, Jan 26, 2017 at 9:42 AM -0600, "Ruchia" <notifications@github.com<mailto:notifications@github.com>> wrote:


The sides of the Analyzing Chamber can be configured to either red or green. Green is for circuits and Red for items. These count as both input and output for these slots.
You can change the side configuration with a wrench. (only with the wrench from Calculator)

You can turn some analysed circuits into upgrades. One of them in the transfer upgrade. When you use this on the Analysing Chamber, it willl attempt to automatically output to a side with a block that accepts input next to it. This will allow you to skip using stuff from other mods, such as ender io conduits and place blocks next to one another another instead.
Another thing you maybe want to know of is the Void Upgrade. When you install this into the Analysing chamber, it will simply discard the secondary outputs (the items) and only keep the circuits.
There's no clear explanation of these items anywhere, if you wonder. The reason maybe because these upgrades react a little bit differently on each machine and may not even install which is the case with most of the machines.
You can install an upgrade by right click using it on one. Instead of opening the interface of the machine, you should get a message in your chat box.

I hope that this information will satisfy you for now.

**Comment by Spaig** [comment]
We're having this glitch too - straight up dupe bugs are often a no no on servers.Any idea when we might have a fix?

**Comment by SonarSonic** [comment]
@Spaig @ShadowWolf666 Are you running the latest version of Sonar Core, Calculator and Ender IO etc. because I also used to get this issue when I tested about a month ago and I found no issues my end. With the latest versions however I don't get the issue at all. Is there any other specifics to your setups?

Potentially Ender IO fixed this.

**Comment by Spaig** [comment]
That was the issue - turns out we had an outdated EIO. Thanks!
