### ISSUE TITLE
[BUG?] CraftTweaker cannot remove a recipe from a calculator.

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#264]
Please fill out the details below before contributing

 * Forge Version: 2422
 * Calculator Version: 3.2.2
 * SonarCore Version: 3.2.8 
 * Multiplayer or Singleplayer: SSP / SMP
 * Crash Report Link: 
 * Affected Features: Mod Integration / CraftTweaker
 * Description: 

I am not sure what's going on, maybe I can't see a mistake here. This line:

```
mods.calculator.basic.removeRecipe(<ore:ingotGold>, <ore:dustRedstone>);
```
is almost directly from your tutorial for it, but CT says "a method available, but **none** matches the parameters (minetweaker.oredict.IOredictEntry, minetweaker.oredict.IOredictEntry) This usually... blabla... removeRecipe(ZenTypeNative).

Now, I have no idea what's going on, I never saw this ZenTypeNative stuff. Adding recipes is working, but removing is not.

**Comment by SonarSonic** [comment]
To remove recipes add the result not the inputs.

**Comment by hron84** [comment]
@SonarSonic then we need better documentation on this and/or an update for [examples](https://gist.github.com/AEnterprise/b209f9bd2432286eaf79) because @AEnterprise removes recipe by ingredients not results and since it is the official documentation of Mine/CraftTweaker integration, it should be definitely more clear.

**Comment by AEnterprise** [comment]
@hron84 my examples where clear, that is the exact script i used back in the day when i originally wrote the original MT code for calculator, things just changed since then

@SonarSonic any other minetweaker changes? maybe you want to make a new one yourself? if not i'll need some better examples and know what else changed (if anything) to update that one
