### ISSUE TITLE
[Question] Transmitters too expenisve?

### ISSUE THREAD

**Issue by thaumictom** [SonarSonic/Calculator#306]
* Forge Version: 14.23.0.2515 (FTB Horizons III)
* Calculator Version: 5.0.1
* SonarCore Version: 5.0.2
* Multiplayer or Singleplayer: Both
* Crash Report Link: None
* Affected Features: None

Hej, I just wanted to ask, if the Transmitters for the Conductor Masts are too expensive. They cost 1 Electric Diamond, 2 Refined Iron, but you only get 1, while for the Weather Stations, you get 4. Is that wanted? Thanks.

**Comment by AEnterprise** [comment]
afaik that is inteded. conductor masts and weather stations are very different things

conductor masts generate power from lightning strikes, weatther stations increase the chanse of that heapening

**Comment by lucasSTU** [comment]
I think he confounded conductor mast and transmitter, but i still think this is intended.
I have played around lightning farm and in my opinion transmitter are stronger than weather station because they upgrade frequency which is equivalent to a multipler to you energy rather than an additive.

conductor mast as it is already pretty busted. Once you have a diamond tree automated and a blaze farm a lightning farm is pretty much free. I think that making transmitter more expensive would not be a bad idea.

**Comment by AEnterprise** [comment]
it could be made more expensive, not sure. balance is a tricky thing in mods like calculator

also i think he thinks they should be cheaper

**Comment by thaumictom** [comment]
Yes, sorry for the bad explanation. Transmitters are over 4x more expensive than Weather Stations, because you only get 1, not 4 like the Weather Stations.

**Comment by andrelinslima** [comment]
The Weather station can only be used by a single mast at a time, while the transmitter can be used by multiple. for example, if you get 4 masts up in the 30 block range around the transmitter it will affect all of them.

I think that one of the reasons why it's pricier.

**Comment by thaumictom** [comment]
Makes sense, but I actually want the Owner's final two cents...

**Comment by AEnterprise** [comment]
i'm pretty sure this is intended balancing, they are already pretty cheap compared to what you get

ollie will reply when he has the time to do so

**Comment by SonarSonic** [comment]
Yes they provide different effects and transmitters have a greater impact on energy generated, hence the difference in price.
