### ISSUE TITLE
Ender IO

### ISSUE THREAD

**Issue by Aknotsdeath** [SonarSonic/Calculator#31]
So I I use ender io conduits to move circuits from one chest to another if one of the chests fills up it keeps moving the circuits thus basically deleting them from existence. So for instance I had 3 chests set up with conduits going between them each so I could fill them all up with circuits after they got cleaned. Only the last chest got filled even though more kept getting made. Not sure if it is Ender IO that has the problem or Calculator mod. If its Ender IO I will post this there.

**Comment by SonarSonic** [comment]
Just normal chests? If your going from Chest-Chest it probably isn't my fault. Or are you pulling them from a Storage Chamber? If your not you might want to think about storing Stable circuits in one storage chamber and normal ones in another instead of using chests. https://github.com/SonarSonic/Calculator/wiki/Storage-Chamber

**Comment by SonarSonic** [comment]
Is this thread dead?

**Comment by Heberdantas** [comment]
Hi, I have a related problem, actually I dont know if my problem is the interaction between enderIO conduits or and my storage chamber or between storage chamber and drawers controller.
I had a TON of circuits in drawers, im playing AoE so i couldnt make the storage chamber before. Now I need to move them to the chamber but only the first slot got filled!

**Comment by SonarSonic** [comment]
@NWBeez should be fixed in the new version I just posted!!
