### ISSUE TITLE
[Issue] Importing cobble via pipes

### ISSUE THREAD

**Issue by DigitalSketch** [SonarSonic/Calculator#342]
Please fill out the details below before contributing

 * Forge Version: 14.23.2.2617
 * Calculator Version: 5.0.3
 * SonarCore Version: 5.0.5
 * Multiplayer or Singleplayer: Single
 * Crash Report Link: 
 * Affected Features: Import/Export via cables
 * Description: connecting (t seems) any type of I/O cable crashes the game.  I've attempted to use Thermal ducts, and XNet, but both crash the server when used to insert cobble into the precision chamber.

**Comment by Tydesson** [comment]
It's not only about cobble. It's about anything.
You cannot also attach an import bus from AE2. If you attach a hopper it's ok since it doesn't seem to want to interact with the inventory, but as soon as you put something INSIDE the hopper, the game crash.

A few crash logs : 
https://pastebin.com/TLYPZ9Rb
https://pastebin.com/1RUz1HSu
https://pastebin.com/ZRKCFx4W

**Comment by SonarSonic** [comment]
Please See #345, Fix should be out later today.
