### ISSUE TITLE
No diamonds from diamond tree

### ISSUE THREAD

**Issue by KamiSami** [SonarSonic/Calculator#383]
Please fill out the details below before contributing

 * Forge Version: forge-14.23.5.2815
 * Calculator Version: 1.12.2-5.0.11-12
 * SonarCore Version: 1.12.2-5.0.19-20
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: No crash
 * Affected Features: Diamond tree
 * Description: The algorithm assimilator or sickle wont collect any diamonds, they appear in inventory when collected with sickle but when you click them they vanish immediately.

**Comment by Ruchian** [comment]
tested, confirmed the following:

Happens in both Singleplayer and Multiplayer. It happens with both the Diamond Tree and Pear Tree.

The Algorythm Assimilator does the following:
First it extracts 1 Weakened Diamond and 1 Flawless Diamond from the tree.
A second later it again extracts 1 Weakened and 1 Flawless Diamond.
After this, a second later it extracts 2 of each.
a second later it extracts 4 of each, then 8, then 16, then 32 and lastly 64.
Once it has reached the speed to extract 64 of each per second it will do so continuesly till the assimilator is full,
Once it is full, it will throw out a stack of 64 of one of the two item types.
After that, the rest of that item type is deleted.
When this has happened, the same thing will happens if you click on a stack to take it out or wait till it reached full state again to throw out the other Diamond type.

Once you break the assimilator, it will receive an NBT tag. Sonar_drop: 0 entries.
Placed again, you can find out it will no longer work.
In fact any algorithm assimilator placed in the world will no longer work on that tree properly. Restarting doesn't help. Only deleting the world and starting over will resolve this issue.
(despite this it will still remove items from the tree, it just fails to produce anything, and yes what I meant is that new assimilators will also not produce anything. They are now all affected by this bug)

However, if you are fast enough, you can still get a few stacks of items in a new world.
I managed to automate extraction of the items at a vast speed. As long as the assimilator isn't full and isn't broken, it will seemingly function, somewhat normally (except that the speed in which it generates items is rediculous)
meaning grabbing stacks of stuff is still possible. So using the automated item extraction, within a couple of seconds to a few minutes I had more than 9000 flawless diamonds.

Oddly as long as they are functioning and never reach full, even when it is broken and placed again it will continue to work like that, eventually giving 64 of each drop every second. 

Placing a second algorithm assimilator in the world working on a different tree of the same type will induce the bug pretty quickly and affect each assimilator. By that I mean they will all stop producing anything from the target tree. (you will also notice with the second assimilator that it doesn't produce two drops, but only one of them for a few stacks)

Minecraft 1.12.2, forge 14.23.5.2815. (Calculator 1.12.2-5.0.11-12, SonarCore 1.12.2-5.0.19-20)
