### ISSUE TITLE
Console Spam Due to Power Network Interaction

### ISSUE THREAD

**Issue by Aubron** [SonarSonic/Calculator#70]
Hey all, I'm an admin of the official /r/feedthebeast server, and we've recently added Calculator to our pack.

However, we do have one particular issue, that I've done my best to boil down into something manageable.

We have some massive console spam that occurs and bloats our FML logs that seems to stem from Calculator machines attached to a power network. This has been occuring on our Cauldron server rather sporadically, and it takes the form of something like this:

http://pastebin.com/CqSb4EMe

I took it upon myself to make the most repeatable possible test case, by making a pack containing only EnderIO, calculator, and dependencies, using the curse voice launcher. this setup, with the starch generator running, will cause the problem:

http://i.imgur.com/C6gayYU.png

Oddly, the spam only happens when I take a screenshot, but I think that's the fault of the launcher's shoddy console implementation.

http://pastebin.com/r7DCYkw1

**Comment by SonarSonic** [comment]
Surprised nobody has found this before to be honest, does Energy interaction no longer work then or is it still functioning?

**Comment by SonarSonic** [comment]
Okay I found the source of the problem. My bad, although I've made some pretty massive changes to Calculator and Sonar Core since the last update to accommodate for changes to Practical Logistics (my other mod) and I won't be able to post a hot fix until I have completed these changes. Sorry for the inconvenience just stay clear of the Advanced Power Cube until then.

**Comment by Aubron** [comment]
Thanks for the response.
